version: "3.9"
services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=telco-cluster
    volumes:
      - cassandra_data:/var/lib/cassandra

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: telco-app
    ports:
      - "5000:5000"
    depends_on:
      - cassandra
      - mongodb
    volumes:
      - .:/app
    environment:
      - CASSANDRA_HOST=cassandra
      - MONGO_HOST=mongodb

volumes:
  cassandra_data:
  mongo_data:
